//go:build ignore

// Generates el_pow10tab.go — the 128-bit power-of-10 table used by EiselLemire.
//
// Each entry is floor(10^e * 2^shift) split into {hi, lo} such that
// the 128-bit value = hi<<64 + lo, with the high bit of hi always set.
//
// This is the standard Eisel-Lemire table format (same as Go stdlib
// internal/strconv/pow10tab.go). It differs from pow10tab.go which
// stores entries in the "hi<<64 - lo" form used by uscale/Parse.
//
// Usage:
//
//	go run el_pow10gen.go

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"math/big"
	"os"
)

const (
	minExp = -348
	maxExp = 347
)

func main() {
	log.SetPrefix("el_pow10gen: ")
	log.SetFlags(0)

	var (
		one = big.NewInt(1)
		ten = big.NewInt(10)

		b1p64  = new(big.Int).Lsh(one, 64)
		b1p128 = new(big.Int).Lsh(one, 128)

		r2     = big.NewRat(2, 1)
		r1p128 = new(big.Rat).SetInt(b1p128)
	)

	var out bytes.Buffer
	fmt.Fprintf(&out, top, minExp, maxExp)
	for e := int64(minExp); e <= maxExp; e++ {
		var r *big.Rat
		if e >= 0 {
			r = new(big.Rat).SetInt(new(big.Int).Exp(ten, big.NewInt(e), nil))
		} else {
			r = new(big.Rat).SetFrac(one, new(big.Int).Exp(ten, big.NewInt(-e), nil))
		}
		be := 0
		for r.Cmp(r1p128) < 0 {
			r.Mul(r, r2)
			be++
		}
		for r.Cmp(r1p128) >= 0 {
			r.Quo(r, r2)
			be--
		}
		d := new(big.Int).Div(r.Num(), r.Denom())
		hi, lo := new(big.Int).DivMod(d, b1p64, new(big.Int))
		fmt.Fprintf(&out, "\t{%#016x, %#016x}, // 1e%d * 2**%d\n", hi.Uint64(), lo.Uint64(), e, be)
	}
	fmt.Fprintf(&out, "}\n")

	src, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile("el_pow10tab.go", src, 0666); err != nil {
		log.Fatal(err)
	}
}

var top = `// Code generated by: go run el_pow10gen.go. DO NOT EDIT.
//
//go:generate go run el_pow10gen.go

package fpparse

const (
	elPow10Min = %d
	elPow10Max = %d
)

// elPow10HiLo holds the {hi, lo} pair for the Eisel-Lemire table.
type elPow10HiLo struct {
	hi uint64
	lo uint64
}

// elPow10Tab holds 128-bit truncated mantissas of powers of 10 for EiselLemire.
// Each entry represents floor(10^e * 2^shift) = hi<<64 + lo, with the high bit set.
var elPow10Tab = [...]elPow10HiLo{
`
