//go:build ignore

// gen_pow5 extracts the Eisel-Lemire 5^q table from the native atof.h into
// pow5_table.go, so both engines round through the same constants.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"strconv"
)

const header = "../../native/ndec/impl/ndec/core/atof.h"

func main() {
	src, err := os.ReadFile(header)
	if err != nil {
		log.Fatal(err)
	}
	def := func(name string) int {
		m := regexp.MustCompile(`#define ` + name + `\s+\(?(-?\d+)\)?`).FindSubmatch(src)
		if m == nil {
			log.Fatalf("%s not found", name)
		}
		v, _ := strconv.Atoi(string(m[1]))
		return v
	}
	smallest, largest := def("ATOF_POW5_128_SMALLEST"), def("ATOF_POW5_128_LARGEST")
	begin := bytes.Index(src, []byte("{{POW5_128_TAB_BEGIN"))
	end := bytes.Index(src, []byte("{{POW5_128_TAB_END}}"))
	if begin < 0 || end < begin {
		log.Fatal("table markers not found")
	}
	pairs := regexp.MustCompile(`\{\s*(0x[0-9a-f]+)ULL,\s*(0x[0-9a-f]+)ULL\s*\}`).FindAllSubmatch(src[begin:end], -1)
	if len(pairs) != largest-smallest+1 {
		log.Fatalf("got %d entries, want %d", len(pairs), largest-smallest+1)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen_pow5.go from %s; DO NOT EDIT.\n\n", "native/ndec/impl/ndec/core/atof.h")
	fmt.Fprintf(&b, "package gdec\n\nconst (\n\tpow5Smallest = %d\n\tpow5Largest = %d\n)\n\n", smallest, largest)
	b.WriteString("// pow5Table holds 5^q normalized to 128 bits, high word first, for q from\n// pow5Smallest.\nvar pow5Table = [...][2]uint64{\n")
	for _, p := range pairs {
		fmt.Fprintf(&b, "\t{%s, %s},\n", p[1], p[2])
	}
	b.WriteString("}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("pow5_table.go", out, 0o644); err != nil {
		log.Fatal(err)
	}
}
